KitwareMedical/ITKUltrasound

- include/itkCurvilinearArraySpecialCoordinatesImage.h
- test/itkCurvilinearArraySpecialCoordinatesImageTest.cxx
This allows a windowed-sinc interpolator to be instantiated.
> BUG: Add Get{Pixel,Neighborhood}Accessor to CurvilinearArray.

- include/itkSliceSeriesSpecialCoordinatesImage.hxx
To work around https://issues.itk.org/jira/browse/ITK-3443
> BUG: Fix SliceSeries multiple calls to SetLargestPossibleRegion

- include/itkSliceSeriesSpecialCoordinatesImage.h
Push the point outside the image so it does not overlap with the point on the
edge.
This could possible be removed or improved in the future.
> ENH: Better handling of TransformIndexToPhysicalPoint outside slices

- include/itkSpecialCoordinatesImageToVTKStructuredGridFilter.hxx
A named point data array appears to be required / useful for the point
interpolator frame work.
> BUG: Set PointData name in ToVTKStructuredGridFilter

- include/itkSpectra1DSupportWindowImageFilter.hxx
Required when this value is used downstream in a pipeline when followed by
Spectra1DImageFilter.
> BUG: populate FFT1DSize in GenerateOutputInformation

- include/itkSpectra1DImageFilter.h
- include/itkSpectra1DImageFilter.hxx
- include/itkSpectra1DSupportWindowImageFilter.h
- wrapping/itkCurvilinearArraySpecialCoordinatesImage.wrap
- wrapping/itkSpectra1DImageFilter.wrap
- wrapping/itkSpectra1DSupportWindowImageFilter.wrap
- wrapping/itkSpectra1DSupportWindowToMaskImageFilter.wrap
When wrapping for python, the use of deque causes errors such as
/home/aylward/src/ITK-Release/Wrapping/Typedefs/itkSpectra1DSupportWindowImageFilter.i:725:
Error: Syntax error in input(3).
The lines throwing the error in the file seem like incomplete/incorrect wrapping specifications for deque:
std::reverse_iterator< std::_Deque_iterator< itkIndex2, const itk::Index< 2 > &, const itk::Index< 2 > * > > crend() const;
unsigned long size() const;
unsigned long max_size() const;
void resize(unsigned long __new_size);
void resize(unsigned long __new_size, itkIndex2 const & __x);
void shrink_to_fit();
bool empty() const;
?unknown? & operator[](unsigned long __n);
?unknown? const & operator[](unsigned long __n) const;
?unknown? & at(unsigned long __n);
?unknown? const & at(unsigned long __n) …
> ENH: std::deque does not wrap for VS2013 or Ubuntu 17.04.  Switching to std::list

- .circleci/config.yml
- .travis.yml
> ENH: Limit macOS Python package builds to 2.7 3.6

- include/itkFrequencyDomain1DFilterFunction.h
To address:
/ITKUltrasound/include/itkFrequencyDomain1DFilterFunction.h: In static
member function 'static itk::FrequencyDomain1DFilterFunction::Pointer
itk::FrequencyDomain1DFilterFunction::New()':
/ITK/Modules/Core/Common/include/itkMacro.h:292:24: error: 'ObjectFactory'
is not a member of 'itk'
Pointer smartPtr = ::itk::ObjectFactory< x >::Create();
> COMP: Add missing ObjectFactory header

- setup.py
- wrapping/CMakeLists.txt
- wrapping/itkSpectra1DSupportWindowImageFilter.wrap
- wrapping/stdlistitkIndex.i.in
To address:
Warning: Unknown parameter 'std::list< itk::Index< 2 > >' in template
'itk::Image'
Warning: Unknown parameter 'std::list< itk::Index< 3 > >' in template
'itk::Image'
Suggested-by: Stephen Aylward <stephen.aylward@kitware.com>
> BUG: Add missing wrapping for itk::Index< std::list >

- include/itkBlockMatchingBlockAffineTransformMetricImageFilter.hxx
To address:
/ITKUltrasound/include/itkBlockMatchingBlockAffineTransformMetricImageFilter.hxx:121:5: error: 'ImageRegionIterator' was not declared in this scope
ImageRegionIterator< FixedImageType > it( m_TransformedFixedImage, this->m_FixedImageRegion );
^~~~~~~~~~~~~~~~~~~
/ITKUltrasound/include/itkBlockMatchingBlockAffineTransformMetricImageFilter.hxx:121:41: error: expected primary-expression before '>' token
ImageRegionIterator< FixedImageType > it( m_TransformedFixedImage, this->m_FixedImageRegion );
^
/ITKUltrasound/include/itkBlockMatchingBlockAffineTransformMetricImageFilter.hxx:123:10: error: 'it' was not declared in this scope
for( it.GoToBegin(); !it.IsAtEnd(); ++it )
^~
> COMP: Add missing itkImageRegionIterator.h include

- include/itkFFTWComplexToComplex1DFFTImageFilter.hxx
- include/itkFFTWForward1DFFTImageFilter.hxx
- include/itkFFTWInverse1DFFTImageFilter.hxx
Todo: rebuild and merge after the next ITK 5 tag and the Python CI images have been updated to support `GetNumberOfWorkUnits`.
> COMP: enable building even with ITK_LEGACY_REMOVE turned ON

- include/itkComplexToComplex1DFFTImageFilter.h
- include/itkForward1DFFTImageFilter.h
- include/itkInverse1DFFTImageFilter.h
This reverts commit 0c5b1ddd7f5a3245b8d7eaac6d602ba5bb0128a9.
These are needed to prevent compiler errors such as:
In file included from test/UltrasoundHeaderTest1.cxx:32:
In file included from /home/matt/src/ITKUltrasound/include/itkVnlInverse1DFFTImageFilter.hxx:21:
In file included from /home/matt/src/ITKUltrasound/include/itkVnlInverse1DFFTImageFilter.h:21:
In file included from /home/matt/src/ITKUltrasound/include/itkInverse1DFFTImageFilter.h:98:
/home/matt/src/ITKUltrasound/include/itkInverse1DFFTImageFilter.hxx:56:12: error: no template named 'VnlInverse1DFFTImageFilter'; did you mean 'Inverse1DFFTImageFilter'?
return VnlInverse1DFFTImageFilter<TInputImage, TOutputImage>::New().GetPointer();
^~~~~~~~~~~~~~~~~~~~~~~~~~
Inverse1DFFTImageFilter …
> Revert "COMP: removing unneeded #ifndefs"

- .github/workflows/build-test-package.yml
Avoid ITK module dependency wheels.
> BUG: Only prepare itk-ultrasound wheels for PyPI upload

- include/itkCurvilinearArraySpecialCoordinatesImage.h
- include/itkSliceSeriesSpecialCoordinatesImage.h
The errors occur in Python wrappings:
```text
------ Build started: Project: UltrasoundPython, Configuration: RelWithDebInfo x64 ------
itkBModeImageFilterPython.cpp
M:\Dev\ITK-git\Modules\Filtering\ImageGrid\include\itkResampleImageFilter.hxx(474,20): error C2672: 'itk::CurvilinearArraySpecialCoordinatesImage<short,2>::TransformPhysicalPointToContinuousIndex': no matching overloaded function found
M:\Dev\ITK-git\Modules\Filtering\ImageGrid\include\itkResampleImageFilter.hxx(441): message : while compiling class template member function 'void itk::ResampleImageFilter<itk::CurvilinearArraySpecialCoordinatesImage<short,2>,itk::Image<short,2>,double,TInterpolatorPrecisionType>::LinearThreadedGenerateData(const itk::ImageRegion<2> &)'
with
[
TInterpolatorPrecisionType=double
] …
```
> ENH: Cover all (Continuous)Index<->PhysicalPoint conversion signatures

- wrapping/CMakeLists.txt
- wrapping/itkAnalyticSignalImageFilter.wrap
- wrapping/itkRegionFromReferenceImageFilter.wrap
Exposes `itkAnalyticSignalImageFilter` and `itkRegionFromReferenceImageFilter` for illustration in example notebook.
> ENH: Add `itkAnalyticSignalImageFilter` and `itkRegionFromReferenceImageFilter` wrappings

- include/itkButterworthBandpass1DFilterFunction.h
Add `;` to the end of statements of the form `itkGetMacro(...)` and `itkSetMacro(...)`.
> STYLE: Add a semicolon to the end of each macro invocation.

- .github/workflows/test-notebooks.yml
Fixes Jupyter Notebook dependency test failure in [https://github.com/KitwareMedical/ITKUltrasound/pull/162](https://github.com/KitwareMedical/ITKUltrasound/pull/162) where Python 3.10 is installed by default but itk-ultrasound packages are only available for 3.6 - 3.9 on PyPi (for now).
Linux Python CI failures are addressed in [https://github.com/KitwareMedical/ITKUltrasound/pull/164](https://github.com/KitwareMedical/ITKUltrasound/pull/164).
> BUG: Fix Jupyter Notebook CI Python Version

- .github/workflows/build-test-package.yml
Linux Python CI includes a cleanup step to work around disk space constraints. It appears that several of these commands are no longer valid and must be removed.
See [ITKVkFFTBackend](https://github.com/InsightSoftwareConsortium/ITKVkFFTBackend/blob/master/.github/workflows/build-test-package.yml) for another example of an external module where cleanup steps have been reduced and CI is passing.
Fixes Linux Python CI failures in [https://github.com/KitwareMedical/ITKUltrasound/pull/162](https://github.com/KitwareMedical/ITKUltrasound/pull/162). Notebook CI failures are addressed in [https://github.com/KitwareMedical/ITKUltrasound/pull/165](https://github.com/KitwareMedical/ITKUltrasound/pull/165).
> BUG: Fix linux python CI runner cleanup step

- examples/PlotPowerSpectra.ipynb
Without it, t the following error is produced on Windows:
'c:\program' is not recognized as an internal or external command,
operable program or batch file.
> Quote sys.executable path in PlotPowerSpectra because of spaces in name

- CMakeLists.txt
Otherwise we run into:
```text
cmake_minimum_required of 3.10.2 is not enough.
CMake Warning at C:/Dev/ITK-git/CMake/ITKModuleExternal.cmake:12 (message):
cmake_minimum_required must be at least 3.16.3
Call Stack (most recent call first):
CMakeLists.txt:105 (include)
This is needed to allow proper setting of CMAKE_MSVC_RUNTIME_LIBRARY.
Do not be surprised if you run into link errors of the style:
error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_Static' doesn't match value 'MDd_Dynamic' in module.obj
```
> ENH: Update the minimum required version of CMake to match ITK 5.3

- itk-module.cmake
- setup.py
Moves ITKVideoCore and ITKVideoIO to TEST_DEPENDS rather than DEPENDS in
order to resolve Python module distribution dependency issue. Closes #175.
> BUG: Make ITKVideo modules test dependencies

- wrapping/CMakeLists.txt
Fixes submodule wrapping to follow user-specified order of classes.
Classes were wrapped in alphabetical order despite an order being manually specified. This resulted in several warnings when loading the `Ultrasound` module in Python:
```
Loading Ultrasound... Warning: Unknown parameter 'itk::CurvilinearArraySpecialCoordinatesImage<float,2>' in template 'itk::BModeImageFilter'
Warning: Unknown parameter 'itk::CurvilinearArraySpecialCoordinatesImage<std::complex<float>,2>' in template 'itk::BModeImageFilter'
Warning: Unknown parameter 'itk::Image<std::list<itk::Index<2>>,2>' in template 'itk::Spectra1DSupportWindowToMaskImageFilter'
Warning: Unknown parameter 'itk::Image<std::list<itk::Index<3>>,3>' in template 'itk::Spectra1DSupportWindowToMaskImageFilter'
Warning: Unknown parameter …
```
> BUG: Set module wrapping order

- include/itkAttenuationImageFilter.h
- include/itkAttenuationImageFilter.hxx
Disables dynamic threading to enforce same-size regions and correctly
use the image region splitter to enforce continuity along scan lines.
Closes #185.
> BUG: Fix `itk::AttenuationImageFilter` region threading

- .github/workflows/build-test-package.yml
- setup.py
Bump to most recent ITK version. May require bumping dependencies first.
> ENH: Bump to ITK v5.3rc04

- include/itkBlockMatchingBlockAffineTransformMetricImageFilter.h
- include/itkBlockMatchingDisplacementPipeline.hxx
- include/itkBlockMatchingMetricImageToDisplacementCalculator.h
- include/itkBlockMatchingMultiResolutionImageRegistrationMethod.h
- include/itkBlockMatchingMultiResolutionIterationCommand.hxx
- include/itkBlockMatchingMultiResolutionIterationObserver.h
- include/itkBlockMatchingNormalizedCrossCorrelationMetricImageFilter.h
- include/itkBlockMatchingNormalizedCrossCorrelationMetricImageFilter.hxx
- include/itkBlockMatchingOptimizingInterpolationDisplacementCalculator.hxx
- include/itkBlockMatchingStrainWindowBlockAffineTransformCommand.hxx
- include/itkLinearLeastSquaresGradientImageFilter.hxx
Remaining error reported when building SlicerITKUltrasound (based of https://github.com/KitwareMedical/SlicerITKUltrasound/pull/78) are like the following:
```
In file included from /home/jcfr/Projects/SlicerITKUltrasound-Release/ITKUltrasound/include/itkBlockMatchingStrainWindowBlockAffineTransformCommand.h:105,
from /home/jcfr/Projects/SlicerITKUltrasound/GenerateDisplacementFromTimeSeries/GenerateDisplacementFromTimeSeries.cxx:38:
/home/jcfr/Projects/SlicerITKUltrasound-Release/ITKUltrasound/include/itkBlockMatchingStrainWindowBlockAffineTransformCommand.hxx: In instantiation of ‘void itk::BlockMatching::StrainWindowBlockAffineTransformCommand<TStrainWindowDisplacemenCalculator, TBlockAffineTransformMetricImageFilter, TStrainImageFilter>::Execute(const itk::Object*, const …
```
> Support build against itk5.3

- setup.py
Bumps ITKUltrasound package to 0.5.4 for tag and distribution on PyPI. Will address #177 where notebooks are failing because they rely on factory mechanisms partially broken in 0.5.3.
See [https://github.com/KitwareMedical/ITKUltrasound/commits/master(https://github.com/KitwareMedical/ITKUltrasound/commits/master) for changes since 0.5.3 tag on April 14th.
> ENH: Bump to 0.5.4

- .github/workflows/test-notebooks.yml
Notebook checks always run with the most recent `itk-ultrasound` PyPI
package release and do not reflect individual PR changes. This updates
the notebook workflow to only run on commits in the `master` branch to
reduce confusion.
Addresses #177. Reference discussion at
https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359 .
> ENH: Remove PR notebook checks

- .github/workflows/build-test-package.yml
- setup.py
Depends on [https://github.com/InsightSoftwareConsortium/ITKHigherOrderAccurateGradient/pull/41](https://github.com/InsightSoftwareConsortium/ITKHigherOrderAccurateGradient/pull/41) and [https://github.com/InsightSoftwareConsortium/ITKMeshToPolyData/pull/50](https://github.com/InsightSoftwareConsortium/ITKMeshToPolyData/pull/50)
> ENH: Bump ITK to v5.3rc04.post2

- .github/workflows/build-test-package.yml
Bumps to ITK reusable workflow to most recent version as of 2.28.2023.
Includes XCode downgrade to address macOS warning:
> KWStyle/kwsCheckLineLength.cxx:24:3: warning: 'sprintf' is deprecated:
This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.
[-Wdeprecated-declarations]
> ENH: Update ITK CI reusable workflow

- wrapping/test/PythonBackscatterImageFilterTest.py
I noticed this during creation of the attenuation Python test.
> STYLE: make the Python test documentation more consistent
